<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wex.Purchases.Contracts\Wex.Purchases.Contracts.csproj" />
    <ProjectReference Include="..\Wex.Purchases.Domain\Wex.Purchases.Domain.csproj" />
    <ProjectReference Include="..\Wex.Purchases.Infrastructure.Treasury\Wex.Purchases.Infrastructure.Treasury.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
  </ItemGroup>

</Project>
