// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wex.Purchases.Infrastructure.Persistence;

#nullable disable

namespace Wex.Purchases.Infrastructure.Persistence.Migrations;

[DbContext(typeof(PurchaseDbContext))]
partial class PurchaseDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Wex.Purchases.Domain.Entities.PurchaseTransaction", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("char(36)")
                    .HasColumnName("id");

                b.Property<decimal>("AmountUsd")
                    .HasPrecision(18, 2)
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("amount_usd");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("description");

                b.Property<DateTime>("TransactionDate")
                    .HasColumnType("datetime(6)")
                    .HasColumnName("transaction_date");

                b.HasKey("Id");

                b.HasIndex("Description")
                    .HasDatabaseName("ix_purchase_transactions_description");

                b.HasIndex("TransactionDate")
                    .HasDatabaseName("ix_purchase_transactions_transaction_date");

                b.ToTable("purchase_transactions");
            });
#pragma warning restore 612, 618
    }
}
